# Mi primera red neuronal

$$
\mathcal{P}(x; w) = sgn(x\, w) = sgn\left( \sum_i x_i w_i \right) 
\quad x, w \in \mathbb{R}^m
$$
con
$$
 sgn(u) = 
  \begin{cases} 
   +1 & \text{if } u \geq 0 \\
   -1 & \text{if } u < 0
  \end{cases}
$$	

En forma vectorial

$$\mathcal{P}(X; W) = sgn\left( X \, W \right) \quad X \in \mathbb{R}^{(n,m)}, \, W \in \mathbb{R}^{(m,1)}$$


## Ejemplo: AND

$$
X = \begin{pmatrix}
  0 & 0 & 1 \\
  0 & 1 & 1 \\
  1 & 0 & 1 \\
  1 & 1 & 1 \\
 \end{pmatrix}
\qquad
\textbf{AND}\left( X \right) = 
 \begin{pmatrix}
  -1 \\
  -1 \\
  -1 \\
  1  \\
 \end{pmatrix}
\qquad
n = 4
$$

$$
\textbf{AND}\left(X \right) = sgn\left( X \,   
    \begin{pmatrix}
      .5 \\
      .5 \\
      -1 \\
    \end{pmatrix} \right)
    \quad
    m = 3
$$

### En python

In [1]:
import numpy as np

In [2]:
# Signo de un numero
def _sgn(u) : return 1 if u >= 0 else -1

# Signo de un tensor
def sgn(t) : return (np.vectorize(_sgn))(t)

In [3]:
# X es una matriz de shape = (4, 3)
X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])

In [4]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [5]:
X.shape

(4, 3)

In [9]:
np.array([.5, .5, -1]).reshape((3,1))

array([[ 0.5],
       [ 0.5],
       [-1. ]])

In [6]:
def AND(X) : 
    W = np.array([.5, .5, -1]).reshape((3,1))
    return sgn(np.matmul(X, W))

In [7]:
AND(X)

array([[-1],
       [-1],
       [-1],
       [ 1]])

##   Implementar AND de la forma X W + b

In [11]:
def AND(X):
    W = np.array([.5, .5]).reshape((2,1))
    b = -1
    return sgn(np.matmul(X, W) + b)


In [12]:
AND(X)

array([[-1],
       [-1],
       [-1],
       [ 1]])

In [14]:
# X es una matriz de shape = (4, 2)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

In [13]:
def AND(X) : 
  W = np.array([.5, .5]).reshape((2,1))
  b = -1
  return sgn(np.matmul(X, W) + b)

In [15]:
AND(X)

array([[-1],
       [-1],
       [-1],
       [ 1]])

# Tarea 1



* **Ejercicio 1**: Utilizando como base el perceptron visto en clase para modelar la función booleana AND, implementar un perceptrón en python para las funciones booleanas definidas en las diapositvas de clase. En caso de no ser posible hacerlo con un perceptron indíquelo y justifique.

  **Ayuda**: Sólo hay que encontrar para cada función booleana el vector de pesos W. La estructura del perceptron y la función de activación son las mismas que las usadas en clase para implementar AND.


+

* **Ejercicio 2**: 
Implementar una red neuronal densa en python que compute simultáneamente todas las funciones booleanas implementadas.

  **Ayuda**: El shape del resultado tiene que ser (,k) dónde k es la cantidad de funciones booleanas implementadas.



In [31]:
# NAND = [1,1,1,-1]
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

def NAND(X) : 
  W = np.array([-.5, -.5]).reshape((2,1))
  b = 0.5
  return sgn(np.matmul(X, W) + b)

NAND(X)

array([[ 1],
       [ 1],
       [ 1],
       [-1]])

In [35]:
# OR = [-1,1,1,1]
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

def OR(X) : 
  W = np.array([.5, .5]).reshape((2,1))
  b = -0.5
  return sgn(np.matmul(X, W) + b)

OR(X)

array([[-1],
       [ 1],
       [ 1],
       [ 1]])

In [83]:
# NOR = [1,-1,-1,-1]

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

def NOR(X) : 
  W = np.array([-2, -2]).reshape((2,1))
  b = 1
  return sgn(np.matmul(X, W) + b)

NOR(X)

array([[ 1],
       [-1],
       [-1],
       [-1]])

In [84]:
# XOR = [-1,1,1,-1]

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

def XOR(X) :
    return AND(np.concatenate((NAND(X), OR(X)), axis=1))

XOR(X)


array([[-1],
       [ 1],
       [ 1],
       [-1]])