# Mi primera red neuronal

$$
\mathcal{P}(x; w) = sgn(x\, w) = sgn\left( \sum_i x_i w_i \right) 
\quad x, w \in \mathbb{R}^m
$$
con
$$
 sgn(u) = 
  \begin{cases} 
   +1 & \text{if } u \geq 0 \\
   -1 & \text{if } u < 0
  \end{cases}
$$	

En forma vectorial

$$\mathcal{P}(X; W) = sgn\left( X \, W \right) \quad X \in \mathbb{R}^{(n,m)}, \, W \in \mathbb{R}^{(m,1)}$$


## Ejemplo: AND

$$
X = \begin{pmatrix}
  0 & 0 & 1 \\
  0 & 1 & 1 \\
  1 & 0 & 1 \\
  1 & 1 & 1 \\
 \end{pmatrix}
\qquad
\textbf{AND}\left( X \right) = 
 \begin{pmatrix}
  -1 \\
  -1 \\
  -1 \\
  1  \\
 \end{pmatrix}
\qquad
n = 4
$$

$$
\textbf{AND}\left(X \right) = sgn\left( X \,   
    \begin{pmatrix}
      .5 \\
      .5 \\
      -1 \\
    \end{pmatrix} \right)
    \quad
    m = 3
$$

### En python

In [15]:
import numpy as np

In [16]:
# Signo de un numero
def _sgn(u) : return 1 if u >= 0 else -1

# Signo de un tensor
def sgn(t) : return (np.vectorize(_sgn))(t)

In [17]:
# X es una matriz de shape = (4, 3)
X = np.array([[0, 0, 1], [0, 1, 1], [1, 0, 1], [1, 1, 1]])

In [18]:
X

array([[0, 0, 1],
       [0, 1, 1],
       [1, 0, 1],
       [1, 1, 1]])

In [19]:
X.shape

(4, 3)

In [20]:
np.array([.5, .5, -1]).reshape((3,1))

array([[ 0.5],
       [ 0.5],
       [-1. ]])

In [21]:
def AND(X) : 
    W = np.array([.5, .5, -1]).reshape((3,1))
    return sgn(np.matmul(X, W))

In [22]:
AND(X)

array([[-1],
       [-1],
       [-1],
       [ 1]])

##   Implementar AND de la forma X W + b

In [33]:
# X es una matriz de shape = (4, 2)
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

In [34]:
def AND(X) : 
  W = np.array([.5, .5]).reshape((2,1))
  b = -1
  return sgn(np.matmul(X, W) + b)

In [35]:
AND(X)

array([[-1],
       [-1],
       [-1],
       [ 1]])

# Tarea 1



* **Ejercicio 1**: Utilizando como base el perceptron visto en clase para modelar la función booleana AND, implementar un perceptrón en python para las funciones booleanas definidas en las diapositvas de clase. En caso de no ser posible hacerlo con un perceptron indíquelo y justifique.

  **Ayuda**: Sólo hay que encontrar para cada función booleana el vector de pesos W. La estructura del perceptron y la función de activación son las mismas que las usadas en clase para implementar AND.


+

* **Ejercicio 2**: 
Implementar una red neuronal densa en python que compute simultáneamente todas las funciones booleanas implementadas.

  **Ayuda**: El shape del resultado tiene que ser (,k) dónde k es la cantidad de funciones booleanas implementadas.



### NAND

In [36]:
# NAND = [1,1,1,-1]
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

def NAND(X) : 
  W = np.array([-.5, -.5]).reshape((2,1))
  b = 0.5
  return sgn(np.matmul(X, W) + b)

NAND(X)

array([[ 1],
       [ 1],
       [ 1],
       [-1]])

### OR

In [37]:
# OR = [-1,1,1,1]
X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

def OR(X) : 
  W = np.array([.5, .5]).reshape((2,1))
  b = -0.5
  return sgn(np.matmul(X, W) + b)

OR(X)

array([[-1],
       [ 1],
       [ 1],
       [ 1]])

### NOR

In [38]:
# NOR = [1,-1,-1,-1]

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

def NOR(X) : 
  W = np.array([-2, -2]).reshape((2,1))
  b = 1
  return sgn(np.matmul(X, W) + b)

NOR(X)

array([[ 1],
       [-1],
       [-1],
       [-1]])

### XOR

La funcion XOR no puede ser modelada por un solo perceptrón porque no es linealmente separable, esto significa que no se puede trazar una sola línea recta (o plano, o hiperplano) para separar salidas 1 de las 0. 

In [40]:
# XOR = [-1,1,1,-1]

X = np.array([[0, 0], [0, 1], [1, 0], [1, 1]])

def XOR(X) :
    return AND(np.concatenate((NAND(X), OR(X)), axis=1))

XOR(X)


array([[-1],
       [ 1],
       [ 1],
       [-1]])

## Ejercicio 2

Implemento una red neuronal multicapa para implementar todas las compuertas. 

Para esto: 

1. Defino los datos de entrenamiento en *X* es decir todas las combinaciones de dos valores booleanos: (0,0), (0,1), (1,0) y (1,1). 
2. Armo las etiquetas combinadas en *y*. Esto representa las etiquetas de salida para las cinco funciones booleanas que implementé: AND, OR, XOR, NOR y NAND. 
    - AND = [0,0,0,1]
    - OR = [0,1,1,1]
    - XOR = [0,1,1,0]
    - NOR = [1,0,0,0]
    - NAND = [1,1,1,0]
3. Armo la red neuronal multicapa: Usando *Sequential* de Keras. El shape de entrada es (4,2) por las 4 combinaciones posibles de valores booleanos y cada combinación es de dos valores. Agrego una capa oculta de 10 neuronas y la combinación tiene un shape de salida de (,5) para la salida correspondiente a las 5 funciones booleanas que se implementaron. 
4. Se utiliza la función de activación *sigmoide* porque queremos que las salida sean 0 o 1. 
5. Utilizo la función de pérdida *binary_crossentropy* y el optimizador *adam*. 
6. Entreno el algoritmo usando *model.fit()* con 5000 epochs.
7. Se toman predicciones para mostrar el resultado. 

In [41]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense

# Datos de entrenamiento
X = np.array([[0,0], [0,1], [1,0], [1,1]]) # Shape = (4,2) por cada combinación de valores de entrada (0,0), (0,1), (1,0), (1,1)

# Etiquetas combinadas (AND, OR, XOR, NOR, NAND) - > Por lo tanto voy a tener un shape de salida (,5)
# AND = [0,0,0,1]
# OR = [0,1,1,1]
# XOR = [0,1,1,0]
# NOR = [1,0,0,0]
# NAND = [1,1,1,0]

y = np.array([[0, 0, 0, 1, 1], [0, 1, 1, 0, 1], [0, 1, 1, 0, 1], [1, 1, 0, 0, 0]])

model = Sequential()
model.add(Dense(10, input_dim=2, activation='sigmoid'))  # Capa oculta con 10 neuronas
model.add(Dense(5, activation='sigmoid'))  # Capa de salida con 5 neuronas (AND, OR, XOR, NOR, NAND)

model.compile(loss='binary_crossentropy', optimizer='adam', metrics=['accuracy'])

model.fit(X, y, epochs=5000, verbose=0)

predictions = model.predict(X)
print(predictions.round())


1/1 [==============================] - 0s 72ms/step
[[0. 0. 0. 1. 1.]
 [0. 1. 1. 0. 1.]
 [0. 1. 1. 0. 1.]
 [1. 1. 0. 0. 0.]]


AND = [0,0,0,1]

OR = [0,1,1,1]

XOR = [0,1,1,0]

NOR = [1,0,0,0]

NAND = [1,1,1,0]

In [43]:
AND_result = predictions[:,0]
OR_result = predictions[:,1]
XOR_result = predictions[:,2]
NOR_result = predictions[:,3]
NAND_result = predictions[:,4]
print("AND: ",AND_result.round())
print("OR: ",OR_result.round())
print("XOR: ",XOR_result.round())
print("NOR: ",NOR_result.round())
print("NAND: ",NAND_result.round())


AND:  [0. 0. 0. 1.]
OR:  [0. 1. 1. 1.]
XOR:  [0. 1. 1. 0.]
NOR:  [1. 0. 0. 0.]
NAND:  [1. 1. 1. 0.]
AND:  [1.7807300e-06 7.8892028e-03 7.0497054e-03 9.8171276e-01]
OR:  [0.01406255 0.9894282  0.9881289  0.9997933 ]
XOR:  [0.0435443  0.9624294  0.96156013 0.0504291 ]
NOR:  [9.8832160e-01 8.4823109e-03 9.8067196e-03 2.2725778e-04]
NAND:  [0.99999994 0.99670076 0.99731326 0.00710872]


In [44]:
# Sin round

print("AND: ",AND_result)
print("OR: ",OR_result)
print("XOR: ",XOR_result)
print("NOR: ",NOR_result)
print("NAND: ",NAND_result)


AND:  [1.7807300e-06 7.8892028e-03 7.0497054e-03 9.8171276e-01]
OR:  [0.01406255 0.9894282  0.9881289  0.9997933 ]
XOR:  [0.0435443  0.9624294  0.96156013 0.0504291 ]
NOR:  [9.8832160e-01 8.4823109e-03 9.8067196e-03 2.2725778e-04]
NAND:  [0.99999994 0.99670076 0.99731326 0.00710872]
